name: user_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.5.3
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  modal_progress_hud_nsn: ^0.5.1
  fluttertoast: ^8.2.8
  flutter_spinkit: ^5.2.1
  sizer: ^3.0.4
  gap: ^3.0.1
  get_it: ^8.0.0
  flutter_launcher_icons: ^0.14.1
  uuid: ^4.5.1
  firebase_storage: ^12.3.3
  cloud_firestore: ^5.4.4
  google_sign_in: ^6.2.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  badges: ^3.1.2
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.3.2
  provider: ^6.1.2
  shimmer: ^3.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  firebase_messaging: ^15.1.6
  rxdart: ^0.28.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13
  json_serializable: ^6.8.0
  freezer: ^0.6.1


 

flutter_icons:
  android: "launcher_icon"
  ios: truecarousel_slider
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/categories/
    - assets/images/carousels/
    - assets/
    - assets/icon.png
